<?php

/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile
?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>

<style>
    .products.wrapper.grid .product-item .product-item-info .product-item-details{
        padding: 0 !important;
        top:-45px !important;
    }
</style>



<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_aloHelper = $this->helper('Magiccart\Alothemes\Helper\Data');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?php echo $block->getToolbarHtml() ?>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $showAddto = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;

        echo $_aloHelper->getGridStyle('.product-items .product-item'); // Config Product Grid
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $showAddto = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>

    <div class="category-products clearfix products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <div class="product-item-info category-products-grid" data-container="product-grid">
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <div class="images-container">
                        <?php
                        $product_label = $_aloHelper->getLabels($_product);
                        echo $product_label ? '<div class="product-label">' . $product_label . '</div>' : '';
                        ?>
                        <div class="product-hover">
                            <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                                <?php echo $productImage->toHtml(); ?>
                            </a>   
                            <?php if ($block->getMode() == 'grid'): ?>
                                <div data-role="add-to-links" class="actions-secondary add-to-links"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                                    <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                        <a href="#"
                                           class="action towishlist link-wishlist"
                                           title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                           aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                           data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
                                           data-action="add-to-wishlist"
                                           role="button">
                                           <!-- <i class="fa fa-heart-o icon"></i> -->
                                            <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                        </a>
                                    <?php endif; ?>
                                    <?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
$_helper = $this->helper(Magento\Catalog\Helper\Output::class);
$_alobHelper = $this->helper('Magiccart\Alothemes\Helper\Data');
?>
<?php
    $blockTabs     = $_alobHelper->getBlockTab();
    $attributeTabs = $_alobHelper->getAttributeTab();
?>
<?php if ($detailedInfoGroup = $block->getGroupChildNames('detailed_info', 'getChildHtml')):?>
    <div class="product info detailed">
        <?php $layout = $block->getLayout(); ?>
        <div class="product data items" data-mage-init='{"tabs":{"openedState":"active"}}'>
            <?php $content = ''; ?>
            <div class="items-tabs">
            <?php foreach ($detailedInfoGroup as $name):?>
                <?php
                    $html = $layout->renderElement($name);
                    if (!trim($html)) {
                        continue;
                    }
                    $alias = $layout->getElementAlias($name);
                    $label = $block->getChildData($alias, 'title');
                ?>
                <div class="data item title"
                     aria-labeledby="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>-title"
                     data-role="collapsible" id="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>">
                    <a class="data switch"
                       tabindex="-1"
                       data-toggle="switch"
                       href="#<?php /* @escapeNotVerified */ echo $alias; ?>"
                       id="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>-title">
                        <?php /* @escapeNotVerified */ echo $label; ?>
                    </a>
                </div>
                <!-- <div class="data item content" id="<?php /* @escapeNotVerified  echo $alias; */ ?>" data-role="content">
                    <?php /* @escapeNotVerified echo $html; */ ?>
                </div> -->

                <?php $content .= '<div class="data item content" id="'.$alias.'" data-role="content">'.$html.'</div>' ?>
            <?php endforeach;?>
            <?php foreach ($blockTabs as $tab):?>
                <?php 
                    if( !isset($tab['enabled'])) {
                        continue;
                    }
                    $alias = $tab['block'];
                    $html  = $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($alias)->toHtml();
                    if (!trim($html)) {
                        continue;
                    }
                    $label = $tab['title'];
                ?>
                <div class="data item title"
                     aria-labeledby="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>-title"
                     data-role="collapsible" id="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>">
                    <a class="data switch"
                       tabindex="-1"
                       data-toggle="switch"
                       href="#<?php /* @escapeNotVerified */ echo $alias; ?>"
                       id="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>-title">
                        <?php /* @escapeNotVerified */ echo $label; ?>
                    </a>
                </div>
                <?php $content .= '<div class="data item content" id="'.$alias.'" data-role="content">'.$html.'</div>' ?>
            <?php endforeach;?>
            <?php foreach ($attributeTabs as $tab):?>
                <?php 
                    if( !isset($tab['enabled']) ) {
                        continue;
                    }
                    $alias   = $tab['attribute'];
                    $blockAttribute = $this->getLayout()->createBlock('Magento\Catalog\Block\Product\View\Attributes');
                    $_product = $blockAttribute->getProduct();
                    $dataAttribute  = $blockAttribute->getAdditionalData();
                    $html = '';
                    if(isset($dataAttribute[$alias])) :
                        $_data = $dataAttribute[$alias];
                        $html .= '<table class="data table additional-attributes ' . $_data['code'] . '">';
                        $html .= '<tbody>';
                        $html .= '<tr>';
                        $html .=    '<th class="col label" scope="row">' . $block->escapeHtml($_data['label']) . '</th>';
                        $html .=    '<td class="col data" data-th="' . $block->escapeHtmlAttr($_data['label']) . '">' . $_helper->productAttribute($_product, $_data['value'], $_data['code']) . '</td>';
                        $html .= '</tr>';
                        $html .= '</tbody>';
                        $html .= '</table>';
                    else :
                        $attributeContent  = $this->helper('Magento\Catalog\Helper\Output')->productAttribute($_product, $_product->getData($alias), $alias);
                        $html .= is_string($attributeContent) ? $attributeContent : __('The attribute %1 not support show on frontend please choose another attribute.', $alias);
                    endif;
                    if ( !trim($html)) {
                        continue;
                    }
                    $label = $tab['title'];
                ?>
                <div class="data item title"
                     aria-labeledby="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>-title"
                     data-role="collapsible" id="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>">
                    <a class="data switch"
                       tabindex="-1"
                       data-toggle="switch"
                       href="#<?php /* @escapeNotVerified */ echo $alias; ?>"
                       id="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>-title">
                        <?php /* @escapeNotVerified */ echo $label; ?>
                    </a>
                </div>
                <?php $content .= '<div class="data item content" id="'.$alias.'" data-role="content">'.$html.'</div>' ?>
            <?php endforeach;?>
            </div>
            <div class="data-tabs-content">
                <?php echo $content ?>
            </div>    
        </div>
    </div>
<?php endif; ?>

                                    <?php
                                    $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                    ?>
<!--                                    <a href="#"
                                       class="action tocompare"
                                       title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                       aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                       data-post='<?php echo $compareHelper->getPostDataParams($_product); ?>'
                                       role="button">
                                        <i class="fa fa-exchange icon"></i> 
                                        <span><?php echo __('Add to Compare') ?></span>
                                    </a>-->
                                    <div class="link-view">
                                        <button type="button" class="quickview <?php echo $_product->getTypeId() ?>"  title="<?php echo $block->escapeHtml(__('Quick View')); ?>" onclick="jQuery.fn.quickview({url: '<?php echo $this->getUrl('alothemes/product/view', array('id' => $_product->getId(), '_type' => 'direct_link', '_secure' => $this->getRequest()->isSecure())) ?>'});"><span><!-- <i class="fa fa-eye icon"></i> --><?php echo __('Quick View') ?></span>
                                        </button>
                                    </div>
                                </div>       
                            <?php endif; ?>                          
                        </div>
                    </div>
                    <div class="product details product-item-details  products-textlink clearfix">
                        <?php
                        $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <h2 class="product name product-name product-item-name">
                            <a class="product-item-link"
                               href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                   <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                            </a>
                        </h2>
                        <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                        <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>                        
                        <?php if ($_product->getIsSalable()): ?>
                            <div class="stock available"><label><?php /* @escapeNotVerified */ echo __('Availability:') ?> </label><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                        <?php else: ?>
                            <div class="stock unavailable"><label><?php /* @escapeNotVerified */ echo __('Availability:') ?> </label><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                        <?php endif; ?>
                        <?php if ($showAddto): ?> <?php /* @showAddto */ ?>
                            <div class="product-item-inner">
                                <?php if ($showDescription): ?>
                                    <div class="product description product-item-description">
                                        <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                        <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */ echo $_productNameStripped ?>"
                                           class="action more"><?php /* @escapeNotVerified */ echo __('Learn More') ?></a>
                                    </div>
                                <?php endif; ?>
                                <?php echo $block->getProductDetailsHtml($_product); ?>
                                <div class="product actions-no product-item-actions clearfix"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                    <div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                        <?php if ($_product->isSaleable()): ?>
                                            <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                            <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                                <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                                <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                                <?php echo $block->getBlockHtml('formkey') ?>
                                                <button type="submit"
                                                        title="<?php echo $block->escapeHtml(__('Add to Bag')); ?>"
                                                        class="action tocart primary button btn-cart">
                                                    <span style="opacity: 1;border: none;color: white;"><?php /* @escapeNotVerified */ echo __('Add to Bag') ?></span>
                                                </button>
                                            </form>
                                        <?php else: ?>
                                            <?php if ($_product->getIsSalable()): ?>
                                                <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                            <?php else: ?>
                                                <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    </div>
                                    <div data-role="add-to-links" class="actions-secondary add-to-links"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                                        <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                            <a href="#"
                                               class="action towishlist link-wishlist"
                                               title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                               aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                               data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
                                               data-action="add-to-wishlist"
                                               role="button">
                                                <!-- <i class="fa fa-heart-o icon"></i> -->
                                                <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                            </a>
                                        <?php endif; ?>
                                        <?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
$_helper = $this->helper(Magento\Catalog\Helper\Output::class);
$_alobHelper = $this->helper('Magiccart\Alothemes\Helper\Data');
?>
<?php
    $blockTabs     = $_alobHelper->getBlockTab();
    $attributeTabs = $_alobHelper->getAttributeTab();
?>
<?php if ($detailedInfoGroup = $block->getGroupChildNames('detailed_info', 'getChildHtml')):?>
    <div class="product info detailed">
        <?php $layout = $block->getLayout(); ?>
        <div class="product data items" data-mage-init='{"tabs":{"openedState":"active"}}'>
            <?php $content = ''; ?>
            <div class="items-tabs">
            <?php foreach ($detailedInfoGroup as $name):?>
                <?php
                    $html = $layout->renderElement($name);
                    if (!trim($html)) {
                        continue;
                    }
                    $alias = $layout->getElementAlias($name);
                    $label = $block->getChildData($alias, 'title');
                ?>
                <div class="data item title"
                     aria-labeledby="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>-title"
                     data-role="collapsible" id="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>">
                    <a class="data switch"
                       tabindex="-1"
                       data-toggle="switch"
                       href="#<?php /* @escapeNotVerified */ echo $alias; ?>"
                       id="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>-title">
                        <?php /* @escapeNotVerified */ echo $label; ?>
                    </a>
                </div>
                <!-- <div class="data item content" id="<?php /* @escapeNotVerified  echo $alias; */ ?>" data-role="content">
                    <?php /* @escapeNotVerified echo $html; */ ?>
                </div> -->

                <?php $content .= '<div class="data item content" id="'.$alias.'" data-role="content">'.$html.'</div>' ?>
            <?php endforeach;?>
            <?php foreach ($blockTabs as $tab):?>
                <?php 
                    if( !isset($tab['enabled'])) {
                        continue;
                    }
                    $alias = $tab['block'];
                    $html  = $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($alias)->toHtml();
                    if (!trim($html)) {
                        continue;
                    }
                    $label = $tab['title'];
                ?>
                <div class="data item title"
                     aria-labeledby="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>-title"
                     data-role="collapsible" id="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>">
                    <a class="data switch"
                       tabindex="-1"
                       data-toggle="switch"
                       href="#<?php /* @escapeNotVerified */ echo $alias; ?>"
                       id="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>-title">
                        <?php /* @escapeNotVerified */ echo $label; ?>
                    </a>
                </div>
                <?php $content .= '<div class="data item content" id="'.$alias.'" data-role="content">'.$html.'</div>' ?>
            <?php endforeach;?>
            <?php foreach ($attributeTabs as $tab):?>
                <?php 
                    if( !isset($tab['enabled']) ) {
                        continue;
                    }
                    $alias   = $tab['attribute'];
                    $blockAttribute = $this->getLayout()->createBlock('Magento\Catalog\Block\Product\View\Attributes');
                    $_product = $blockAttribute->getProduct();
                    $dataAttribute  = $blockAttribute->getAdditionalData();
                    $html = '';
                    if(isset($dataAttribute[$alias])) :
                        $_data = $dataAttribute[$alias];
                        $html .= '<table class="data table additional-attributes ' . $_data['code'] . '">';
                        $html .= '<tbody>';
                        $html .= '<tr>';
                        $html .=    '<th class="col label" scope="row">' . $block->escapeHtml($_data['label']) . '</th>';
                        $html .=    '<td class="col data" data-th="' . $block->escapeHtmlAttr($_data['label']) . '">' . $_helper->productAttribute($_product, $_data['value'], $_data['code']) . '</td>';
                        $html .= '</tr>';
                        $html .= '</tbody>';
                        $html .= '</table>';
                    else :
                        $attributeContent  = $this->helper('Magento\Catalog\Helper\Output')->productAttribute($_product, $_product->getData($alias), $alias);
                        $html .= is_string($attributeContent) ? $attributeContent : __('The attribute %1 not support show on frontend please choose another attribute.', $alias);
                    endif;
                    if ( !trim($html)) {
                        continue;
                    }
                    $label = $tab['title'];
                ?>
                <div class="data item title"
                     aria-labeledby="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>-title"
                     data-role="collapsible" id="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>">
                    <a class="data switch"
                       tabindex="-1"
                       data-toggle="switch"
                       href="#<?php /* @escapeNotVerified */ echo $alias; ?>"
                       id="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>-title">
                        <?php /* @escapeNotVerified */ echo $label; ?>
                    </a>
                </div>
                <?php $content .= '<div class="data item content" id="'.$alias.'" data-role="content">'.$html.'</div>' ?>
            <?php endforeach;?>
            </div>
            <div class="data-tabs-content">
                <?php echo $content ?>
            </div>    
        </div>
    </div>
<?php endif; ?>

                                        <?php
                                        $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                        ?>
<!--                                        <a href="#"
                                           class="action tocompare"
                                           title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                           aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                           data-post='<?php echo $compareHelper->getPostDataParams($_product); ?>'
                                           role="button">
                                             <i class="fa fa-exchange icon"></i> 
                                            <span><?php echo __('Add to Compare') ?></span>
                                        </a>-->
                                    </div>
                                </div>
                            </div>
                        <?php endif; /* End showAddto */ ?>                                       
                    </div>
                    <?php if ($block->getMode() == 'grid'): ?>
                        <div class="hover-box clearfix">
                            <div class="product actions product-item-actions show-box"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                <div class="actions-primary actions-cart"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                            <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                            <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                            <?php echo $block->getBlockHtml('formkey') ?>
                                            <div class="field qty" style="float: left;width: 100%; border: 2px solid #ddd;margin-bottom: 10px;z-index: 999;background: white;">
                                                <div class="control control-qty-cart" style="width: 100%;">
                                                    <div class="control-qty" style="width: 100%;">
                                                        <span style="width: 25% !important;float: left;font-size: 32px;text-align: center;" class="quantity-controls quantity-minus">-</span>
                                                        <input style="width: 50% !important;text-align: center;border: none !important;" type="number" name="qty"  maxlength="12" value="<?php /* @escapeNotVerified */
                                            echo '1';
                                            ?>" title="<?php /* @escapeNotVerified */
                                            echo __('Qty')
                                            ?>" class="qty-default input-text qty"
                                                               data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                                                               />            
                                                        <span style="width: 25% !important;float: right;font-size: 32px;text-align: center;" class="quantity-controls quantity-plus">+</span>

                                                    </div>
                                                </div>
                                            </div>
                                            <button type="submit" style= "background: transparent linear-gradient(279deg, #EECAC679 0%, #DEC9CE 46%, #B5C6E5 100%) 0% 0% no-repeat padding-box;opacity: 1;border: none;color: white;"
                                                    title="<?php echo $block->escapeHtml(__('Add to Bag')); ?>"
                                                    class="action tocart primary button btn-cart pull-left-none">
                                                <span> <?php /* @escapeNotVerified */ echo __('Add to Bag') ?></span>
                                            </button>
                                        </form>
                                    <?php else: ?>
                                        <?php if ($_product->getIsSalable()): ?>
                                            <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                        <?php endif; ?>
            <?php endif; ?>
                                </div>                         
                            </div>                                   
                        </div>
                <?php endif; ?>       
                </div>
                <?php echo($iterator == count($_productCollection) + 1) ? '</li>' : '' ?>
    <?php endforeach; ?>
        </ol>
    </div>
    <!-- <div class="toolbar-bottom "> -->
    <div class="toolbar-bottom toolbar-view-<?php echo $viewMode; ?>">
    <?php echo $block->getToolbarHtml() ?>
    </div>
    <!-- </div> -->
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
            {
            "[data-role=tocart-form], .form.map.checkout": {
            "catalogAddToCart": {}
            }
            }
        </script>
    <?php endif; ?>
<?php endif; ?>

<script type="text/javascript">
    require([
        'jquery'
    ], function ($) {
        $('.quantity-plus').click(function () {
            // $('.qty-default').val(Number($('.qty-default').val()) + 1);
            var currentQTY = parseInt($(this).parent().parent().find(".qty-default").val());
            currentQTY = currentQTY + 1;
            $(this).parent().parent().find(".qty-default").val(currentQTY);
        });

        $('.quantity-minus').click(function () {
            // var value = Number($('.qty-default').val()) - 1;
            var currentQTY = parseInt($(this).parent().parent().find(".qty-default").val());
            currentQTY = currentQTY - 1;
            if (currentQTY > 0) {
                $(this).parent().parent().find(".qty-default").val(currentQTY);
            }
        });
    });
</script>